# Change these first
owner: One-Future-Unified-Team # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Main Site
    url: https://one-future-unified-team.github.io/
  - name: Web App
    url: https://one-future-unified-team.github.io/Web-App/
  - name: Documentation
    url: https://one-future-unified-team.github.io/Documentation/
  - name: Store
    url: https://one-future-unified-team.github.io/Store/

status-website:
  baseUrl: status.onefutureunifiedteam.tk
  logoUrl: https://one-future-unified-team.github.io/logo.png
  name: OFUT Status
  introTitle: "One Future Unified Team Status"
  introMessage: Welcome to the official status page of One Future Unified Team. A place to know more about the status of One Future Unified Team website, project, software and app. We currently provide live updates of all of our website, project, software and app status in this page for you to know.<br><br>One Future Unified Team is a small team based in Malaysia. One Future Unified Team is focused in many things, from web development to story writing. One Future Unified Team is founded from a group of young friends with an interest in technology.
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: https://one-future-unified-team.github.io/
    - title: Web App
      href: https://one-future-unified-team.github.io/Web-App
    - title: Documentation
      href: https://one-future-unified-team.github.io/Documentation
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: One Future Unified Team Status is totally [open source]($REPO) for everyone in the world to read and study our codes anytime in the year. 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
